version: "3.9"
services:
  hexo:
    build:
      context: .
      args:
        NODE_VERSION: 16
    container_name: hexo
    #image: hexo-blog:latest
    restart: always
    environment:
      HEXO_SERVER_PORT: 5000
    ports:
      - '38801:5000'
    volumes:
      - ./data/hexo:/hexo
networks:
  default:
    name: docker_network
    external: true
