version: "3.9"
services:
  hexo:
    build:
      context: .
      args:
        NODE_VERSION: 16
    container_name: hexo
    restart: always
    environment:
      HEXO_SERVER_PORT: 5000
    ports:
    - '8080:5000'
    volumes:
    - ./data/hexo:/hexo
networks:
  default:
    name: docker_network
    external: true
